### ISSUE TITLE
Different syntax highlite scss vs sass

### ISSUE THREAD

**Issue by jalberto** [serenadeai/tree-sitter-scss#12]
So this happens if I open a `sass`file while `ft=sass`

![image](https://user-images.githubusercontent.com/99927/169506407-4453892e-45b7-432b-b013-c5520912260b.png)

and this when `ft=scss`

![image](https://user-images.githubusercontent.com/99927/169506480-ece2e930-7221-442b-8c3f-2deff3bdbc5d.png)

Is this expected?

**Comment by tmacwill** [comment]
hi there! thanks for the report. this tree-sitter grammar only supports SCSS syntax, not SASS syntax, at the moment.

**Comment by jalberto** [comment]
Is it part of the plan to support `sass` syntax?

**Comment by tmacwill** [comment]
hmm, I think it'd make sense for `sass` to be a separate grammar, but could also live in this repo. I don't have an ETA on adding one here, but certainly open to PRs!

**Comment by jalberto** [comment]
The items/elements syntax wide are the same, actually setting a `sas` file
to `scss` kind of works
