### ISSUE TITLE
Negative numbers don't get seen as an integer

### ISSUE THREAD

**Issue by benfrain** [serenadeai/tree-sitter-scss#8]
![image](https://user-images.githubusercontent.com/1318466/145072444-5452f258-041a-48eb-af50-5f299d47eb2d.png)

Rules containing negative number values don't get parsed as an integer.

This isn't an issue with standard CSS files so looks to be something specific to scss.

**Comment by EdenEast** [comment]
For reference this was resolved in [tree-sitter/tree-sitter-css#12](https://github.com/tree-sitter/tree-sitter-css/pull/12)
