### ISSUE TITLE
Values and properties not differentiated

### ISSUE THREAD

**Issue by benfrain** [serenadeai/tree-sitter-scss#9]
In CSS syntax, properties and values get a different colouring.

In this scss parser, properties and values get the same. Would it be possible to get different treatment for property/values?

CSS:

![image](https://user-images.githubusercontent.com/1318466/145073508-939262f4-a3de-4b5d-83bd-6f12fe28b61b.png)

SCSS:

![image](https://user-images.githubusercontent.com/1318466/145081322-328239ac-df96-4caa-a531-39e3a49aeaa1.png)

**Comment by tmacwill** [comment]
hi there! this grammar should already produce a tree with separate nodes for property names and values—here's an example from the tests. might the issue be related to the nvim theme instead? am going to close this, but feel free to reopen if there's a particular source block that's not being parsed correctly.

```
a {
  b: c !important;
}

---

(stylesheet
  (rule_set
    (selectors (tag_name))
    (block
      (declaration (property_name) (plain_value) (important)))))
```

**Comment by benfrain** [comment]
Hi, the example above is using the same theme for each screenshot. Are you seeing the value display in a different color in your theme?

**Comment by tmacwill** [comment]
I'm not super familiar with neovim themes, just looking at the trees produced by tree-sitter :)

the source from your example:

```
.here {
  top: 19px;
  bottom: -10px;
  display: block;
  position: absolute;
  grid-template-columns: auto 1fr;
}
```

parses to this tree:

```
(stylesheet (rule_set (selectors (class_selector (class_name))) (block (declaration (property_name) (integer_value (unit))) (declaration (property_name) (integer_value (unit))) (declaration (property_name) (plain_value)) (declaration (property_name) (plain_value)) (declaration (property_name) (plain_value) (integer_value (unit))))))
```

which appears to have names and values in separate nodes, as expected. there could be a particular piece of syntax that's parsing in `tree-sitter-css` but not `tree-sitter-scss`, so if you have a minimal example that reproduces the error, I'd be happy to take a look.
